---
title: "Instruments"
format:
  html:
    toc: true
---
## Overview
The pipe organ has a vast history extending to [ancient Alexandria](https://en.wikipedia.org/wiki/Water_organ), but the instrument began to more closely resemble what we see today [during the Middle Ages](https://en.wikipedia.org/wiki/Pipe_organ#Medieval) in Europe, where it became a staple of Roman Catholic liturgy. Although instruments across the continent had similar traits and mechanics, by the Baroque era there were sweeping regional differences in construction and especially in tonal design. Even though the centuries of intervening development and global diffusion of technique mean that, for example, French Romantic traits can be observed in instruments from Charlestown to China, one can still identify national schools of organbuilding in modern-day work. 

On a more concrete level, each organbuilder and each instrument for the most part are quite unique. The design and execution of a pipe organ (both visual and tonal) has always been a lengthy endeavor highly influenced both by prevailing stylistic ideals and the acoustical parameters of the church or hall for which it is built. Add to this variety the observation that no two stops of the same name on two different instruments ever sound fully alike (for even if they are built identically they are subject to different acoustics), and comparative analysis of pipe organs becomes quite a fascinating subject.

Here the sheer volume of the Internet comes into play.

## [Stop](https://en.wikipedia.org/wiki/Organ_stop) Name References
If uncertain as to what a stop name means, see this [brief table](https://en.wikipedia.org/wiki/List_of_pipe_organ_stops) (Wikipedia) or the online [Encyclopedia of Organ Stops](http://www.organstops.org/), which also has some sound clips of registers in isolation (mostly from digital samplesets in turn recorded from actual instruments).

## General Databases
These contain detailed stoplists, photographs, and historical information for many of the world's pipe organs. Most are limited to a particular country or region. There is a good chance that any large acoustic pipe organ heard in a recording or on YouTube can be found on one of these sites.

### [Die Orgelseite](https://die-orgelseite.de/index_e.html) (Germany/Global)
Although much of the content is behind a paywall, the site provides stoplists and photos for the largest instruments in Germany, the US, and some others.
There is also a [ranked list](https://die-orgelseite.de/orgelliste_001_e.htm) of the largest instruments and a [list of uncommon features](https://die-orgelseite.de/kurioses_e.htm) of certain instruments. 

### [pipeorgandatabase.org](https://pipeorgandatabase.org/) (USA/North America)
Created by the [Organ Historical Society](https://organhistoricalsociety.org/). Contains information on over 70,000 pipe organs in the US (!), with many excellent photographs. 

### [The National Pipe Organ Register](https://npor.org.uk/) (UK)

### [Inventory of Organs](https://inventaire-des-orgues.fr/orgues/?page=1&sort=completion:desc) (France)

### [The Organs of Paris](https://organsofparis.eu/index.htm) (Paris, France)
Detailed information on the [about 278](https://organsofparis.eu/allorgans.htm) pipe organs in Paris, including a [historical breakdown](https://organsofparis.eu/br.htm) of when they were built.

## Builder's Lists
Most current and some former organbuilders maintain lists of their instruments. A few such are:

### [Skinner/Aeolian-Skinner](https://organhistoricalsociety.org/aeolianskinner/) (formerly of Methuen and Boston, MA)
Lists of factory specifications; a few photographs. Aeolian-Skinner was the definitive American Classic organbuilder under [G. Donald Harrison](https://en.wikipedia.org/wiki/G._Donald_Harrison) in the early-to-mid 20th century.

### [Casavant](https://www.casavant.ca/home/) (Saint-Hyacinthe, Quebec)
One of the oldest and most prolific builders in North America. Site contains photos of over 30 curated instruments with descriptions and stoplists.

### [C.B. Fisk](https://cbfisk.com/instruments/) (Gloucester, MA)
A leading American mechanical-action builder and pioneer of the use of carbon fiber for tracker action. Site has a geographical list of most of their work.

More North American builders can be found at the website of the [Associated Pipe Organ Builders of America](https://apoba.com/members/view/all/)